import SupabaseProvider from '@/auth/provider/SupabaseProvider';
import Header from '@/core/components/Header';

import '@/styles/globals.css';

export const metadata = {
  title: 'Boniche Gang',
  description: 'Generated by Next.js'
};

export default async function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className="flex flex-col min-h-screen bg-slate-50"
        suppressHydrationWarning={true}
      >
        <SupabaseProvider>
          {/* @ts-expect-error Async Server Component */}
          <Header />
          <main className="flex flex-col px-4 pb-12 md:px-10 flex-grow">
            {children}
          </main>
        </SupabaseProvider>
      </body>
    </html>
  );
}
