import Header from '@/core/components/Header';
import SupabaseProvider from '@/auth/provider/supabase-provider';

import '@/styles/globals.css';

export const metadata = {
  title: 'Boniche Gang',
  description: 'Generated by Next.js'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className="flex flex-col min-h-screen bg-slate-50"
        suppressHydrationWarning={true}
      >
        <Header />
        <SupabaseProvider>
          <main className="flex flex-col p-4 md:p-10 flex-grow">
            {children}
          </main>
        </SupabaseProvider>
      </body>
    </html>
  );
}
