import '@styles/globals.css';

export const metadata = {
  title: 'Boniche Gang',
  description: 'Generated by Next.js'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className="p-4 md:p-10 mx-auto max-w-7xl">{children}</main>
      </body>
    </html>
  );
}
